/* 
 * Copyright (C) 2015 Open Source Parking Inc.(www.osparking.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.osparking.osparking;

import static com.osparking.osparking.ControlGUI.show100percentSizeImageOfGate;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import com.osparking.global.names.CarAdmission;
import static com.osparking.global.Globals.*;
import static com.osparking.osparking.Common.resizeComponents;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author Open Source Parking Inc.
 */
public class PanelFor1Gate extends GatePanel {
    final DefaultListModel model_1 = new DefaultListModel();    
    JList entryList[] = new JList[3];
    DefaultListModel models[] = new DefaultListModel[3];
    
    private BufferedImage gateImages[] = new BufferedImage[2]; 
    private JLabel[] CarPicLabels = new JLabel[2];
    private Dimension prevSize = null;
    
    /**
     * Creates new form PanelFor1Gate
     */
    public PanelFor1Gate() {
        initComponents();
        CarPicLabels[1] = CarPicLabel1;  
        entryList[1] = List_Gate1;
        models[1] = model_1;    
        Toolkit.getDefaultToolkit().setDynamicLayout( false );        
        
        addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent evt) {
                Dimension gatesPanelSize = getSize();
                resizeComponents((GatePanel)evt.getSource(), gatesPanelSize);

                if (Panel_Gate1.getSize().equals(prevSize)) {
                    return;
                } else {
                    prevSize = Panel_Gate1.getSize();
                    if (getEntryList(1).getModel().getSize() > 0) 
                    {
                        if (getEntryList(1).getSelectedIndex() == -1) 
                        {
                            getEntryList(1).setSelectedIndex(0);
                        }
                        ControlGUI.showImage(1);
                    }                  
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Gate1 = new javax.swing.JPanel();
        CarPicLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        ScrollPane_Gate1 = new javax.swing.JScrollPane();
        List_Gate1 = new javax.swing.JList();
        RightMargin = new javax.swing.JPanel();
        MarginLabel = new javax.swing.JLabel();

        setBackground(MainBackground);
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        Panel_Gate1.setBackground(MainBackground);
        Panel_Gate1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gate 1 Title", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dotum", 1, 14))); // NOI18N
        Panel_Gate1.setMaximumSize(new Dimension(Short.MAX_VALUE, Short.MAX_VALUE));
        Panel_Gate1.setName("Panel_Gate1"); // NOI18N
        Panel_Gate1.setPreferredSize(new java.awt.Dimension(343, 450));
        Panel_Gate1.setLayout(new javax.swing.BoxLayout(Panel_Gate1, javax.swing.BoxLayout.Y_AXIS));

        CarPicLabel1.setBackground(MainBackground);
        CarPicLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarPicLabel1.setAlignmentX(0.5F);
        CarPicLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CarPicLabel1.setDoubleBuffered(true);
        CarPicLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CarPicLabel1.setIconTextGap(0);
        CarPicLabel1.setMaximumSize(new Dimension(Short.MAX_VALUE, Short.MAX_VALUE));
        CarPicLabel1.setMinimumSize(new java.awt.Dimension(100, 100));
        CarPicLabel1.setName(""); // NOI18N
        CarPicLabel1.setOpaque(true);
        CarPicLabel1.setPreferredSize(new java.awt.Dimension(303, 200));
        CarPicLabel1.setVerifyInputWhenFocusTarget(false);
        CarPicLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CarPicLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarPicLabel1MouseClicked(evt);
            }
        });
        Panel_Gate1.add(CarPicLabel1);
        Panel_Gate1.add(filler1);

        ScrollPane_Gate1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recent Car Arrivals", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Dotum", 1, 13))); // NOI18N
        ScrollPane_Gate1.setPreferredSize(new java.awt.Dimension(302, 155));

        List_Gate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        List_Gate1.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        List_Gate1.setModel((DefaultListModel<CarAdmission>)admissionListModel[1]);
        List_Gate1.setMaximumSize(new Dimension(Short.MAX_VALUE, Short.MAX_VALUE));
        List_Gate1.setMinimumSize(new java.awt.Dimension(45, 240));
        List_Gate1.setName(""); // NOI18N
        List_Gate1.setPreferredSize(new java.awt.Dimension(303, 380));
        ScrollPane_Gate1.setViewportView(List_Gate1);

        Panel_Gate1.add(ScrollPane_Gate1);

        add(Panel_Gate1, java.awt.BorderLayout.LINE_START);

        RightMargin.setBackground(MainBackground);
        RightMargin.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        RightMargin.setMaximumSize(new Dimension(Short.MAX_VALUE, Short.MAX_VALUE));
        RightMargin.setPreferredSize(new java.awt.Dimension(0, 0));
        RightMargin.setLayout(new javax.swing.BoxLayout(RightMargin, javax.swing.BoxLayout.Y_AXIS));

        MarginLabel.setBackground(new java.awt.Color(255, 153, 153));
        MarginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MarginLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MarginLabel.setMaximumSize(new Dimension(Short.MAX_VALUE, Short.MAX_VALUE));
        MarginLabel.setName(""); // NOI18N
        MarginLabel.setPreferredSize(new java.awt.Dimension(200, 500));
        MarginLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RightMargin.add(MarginLabel);

        /*

        add(RightMargin, java.awt.BorderLayout.LINE_END);
        */
    }// </editor-fold>//GEN-END:initComponents

    private void CarPicLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarPicLabel1MouseClicked
        show100percentSizeImageOfGate(1, getGateImages()[1]);
    }//GEN-LAST:event_CarPicLabel1MouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CarPicLabel1;
    public javax.swing.JList List_Gate1;
    private javax.swing.JLabel MarginLabel;
    private javax.swing.JPanel Panel_Gate1;
    private javax.swing.JPanel RightMargin;
    private javax.swing.JScrollPane ScrollPane_Gate1;
    private javax.swing.Box.Filler filler1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displaySizes() {
        StringBuffer sb = new StringBuffer();
        
        sb.append("Whole");         
        sb.append(System.lineSeparator());
        sb.append("Pan = ");        
        sb.append(getSizeString(this));
        sb.append(System.lineSeparator());
        sb.append(System.lineSeparator());
        
        sb.append("Gate1");         
        sb.append(System.lineSeparator());
        sb.append("Pan = ");        
        sb.append(getSizeString(Panel_Gate1));
        sb.append(System.lineSeparator());
        sb.append("PIC = ");        
        sb.append(getSizeString(getCarPicLabels()[1]));
        sb.append(System.lineSeparator());
        sb.append("ScL = ");        
        sb.append(getSizeString(ScrollPane_Gate1));
        sb.append(System.lineSeparator());
        sb.append("LsT = ");        
        sb.append(getSizeString(List_Gate1));
        sb.append(System.lineSeparator());
        sb.append(System.lineSeparator());

        sb.append("Margin");         
        sb.append(System.lineSeparator());
        sb.append("Pan = ");        
        sb.append(getSizeString(getMarginLabel()));
        sb.append(System.lineSeparator());
        sb.append(System.lineSeparator());        
        sb.append("PIC = ");        
        sb.append(getSizeString(MarginLabel));
        sb.append(System.lineSeparator());
        sb.append(System.lineSeparator());        
                
//        JOptionPane.showMessageDialog(null,
//            sb.toString(), "InfoBox: CarPicLabel", JOptionPane.INFORMATION_MESSAGE);   
        System.out.println(sb.toString());
    }

    @Override
    public JList getEntryList(int gateNo) {
        return entryList[gateNo];
    }
    
    @Override
    public DefaultListModel getDefaultListModel(int gateNo) {
        return models[gateNo];
    }    

    @Override
    public JPanel getPanel_Gate(int gateNo) {
        return Panel_Gate1;
    }

    @Override
    public BufferedImage[] getGateImages() {
        return gateImages;
    }

    @Override
    public void setGateImage(byte gateNo, BufferedImage gateImage) {
        this.gateImages[gateNo] = gateImage;
    }

    @Override
    public JLabel[] getCarPicLabels() {
        return CarPicLabels;
    }

    @Override
    public JLabel getMarginLabel() {
        return MarginLabel;
    }
}
